// GENERATED FILE - do not edit by hand.
// Rebuild with `npm run presets`; see scripts/build-presets.mjs.
//
// Decoded from Chakazul/Lenia `Python/animals.json` (Bert Wang-Chak Chan).
// Pattern cells are base64, one byte per cell, value = byte / 255.
// `mu`/`sigma` are Chan's growth m/s; dt = 1 / T. `kn`/`gn` record the
// kernel core and growth function he published for each species.

const decode = (s) => {
    const bin = atob(s);
    const out = new Float32Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i) / 255;
    return out;
};

export const PRESETS = [
    {
        name: "Orbium unicaudatus",
        R: 13,
        dt: 0.1,
        mu: 0.15,
        sigma: 0.015,
        beta: [1],
        kn: 1,
        gn: 1,
        pattern: { w: 20, h: 20, data: "AAAAAAAAAA0EAAAAAAAAPAAAAAAAAAAAAAAjNTYVEhkaEgFBAAAAAAAAAAAAFkRbYlcwLywvLRtZAAAAAAAAAAMRWXR3YSEUDhAfN7QAAAAAAAAJIS9XZ2JIIgAAAAAMZlQAAAEABCMrIhw/RUM1AAAAAAAF3AAAPAAaLBQAADNPXl89AAAAAAB0KAAAHy8cAAAARW2BiYIAAAAAAACEAACWNwgAAAAwh6KurmsAAAAAAG0AAI08AAAAAAeewdbazhsAAAAASBkAAJgAAAAAAKrf9f34jwAAAAA5JAAA1gAAAAAAgff////pRwAABjgiAACNEwAAAABV///6//iOKA0ePhYAAAhyAAAAAC3Z/+Tc3aZVMjc7CgAAAGwdAAAAHZ7g0se9nGhLRCoAAAAAFFUTAAAebKy4raCGZ085EAAAAAAAKkImHixWf46Lf21WPh4AAAAAAAAAJTs8QlFjbGlcTjogBQAAAAAAAAAAEis6QEZHQjsqGAUAAAAAAAAAAAAAAA8aISIeFAsAAAAAAA==" },
    },
    {
        name: "Orbium bicaudatus",
        R: 13,
        dt: 0.1,
        mu: 0.15,
        sigma: 0.014,
        beta: [1],
        kn: 1,
        gn: 1,
        pattern: { w: 20, h: 20, data: "AAAAAAAAAAAAAAAAACMAAAAAAAAAAAAAAAAAAAAAAAAAAEYAAAAAAAAAAAAAABYZAA0dIyEURgAAAAAAAAAAAAIoJlFNNC8nJC0+vAAAAAAAAAAACUJWcGs4CgAAAAc/kwAAAAAAAAAUVHRYVCsAAAAAAAClBAAAAAAAEy8+SjwqQDUAAAAAAACpAAAAAAYsJQwgQDhecFsAAAAAAEUxAAsAGyoHAAVOcnajoD4AAAAAA1oAGQAsFQAAAF+SosDUyx4AAAAASwgAiDgIAAAANqnV1vr7zgwAAAQ8EgAfZwEAAAAAuOv03f//mBMAGDoUAADhBQAAAABj+P+0uvbbZy4wNxAAABZ1AAAAAATp/76jxNGSVUMzBgAAAK8AAAAAAH371rGztY5gRCUAAAAAAHUAAAAANqzNtqWUdVM0DwAAAAAAM0wKAAAoa5eYh3FWOxsAAAAAAAAALEQuJjZSZ2teTDYeBAAAAAAAAAAAETM6QEZIQjgnFAMAAAAAAAAAAAAAAAwXHh0YEAcAAAAAAA==" },
    },
    {
        name: "Gyrorbium gyrans",
        R: 13,
        dt: 0.1,
        mu: 0.156,
        sigma: 0.0224,
        beta: [1],
        kn: 1,
        gn: 1,
        pattern: { w: 21, h: 23, data: "AAAAAAAAAAAAAAUMEREMBQAAAAAAAAAAAAAAABQtODgzMC0mHgwAAAAAAAAAAApejJugm4RgRDgzKBwHAAAAAAAAR3xCIzVtqKp/STAtKyEPAAAAAABZVgAAAAAZkbqMUS0hIx4PAAAAACttAAAAAAAAgsaecGZeKBwMAAAAAJYCAAAAAAAAgv///Pz/9GsMAAAAHJMAAAAAAAAe7////8nE6Og4AAAAVo4AAAAAAAVt2/n/2IJtgsaoAAAAaKMWAAAABRy3xt3RckI4OGa/BQAAWbJ3KBEjKzOtqpMcAAAAAhx/WQAAMJu1oIR3Y1GTelsAAAAAAABHWQAABWut2PLMjl5jTDgAAAAAAAAwTwAAADiO4v/RWSY6KBYAAAAAAAA6NQAAAAp15f9gAAAAAAAAAAAAAB5CCgAAAABZ6MkhAAAAAAAAAAAAIzoUAAAAAAA63aAjAgAAAAAAAAAzKAAAAAAAAAAFt7UoDwAAAAAAFE84AAAAAAAAAAAAY/81IQ8FAg84NXJ/AAAAAAAAAAAAAOVtOjMwOkIhP5N6ZgAAAAAAAAAAAADoSUQ9KwUAW21UQjgWABQrAAAAAAAArUwFAAAWKAIAAAAAAAAAAAAAAAAAACFWOCMRAAAAAAAAAAAA" },
    },
    {
        name: "Hydrogeminium natans",
        R: 18,
        dt: 0.1,
        mu: 0.26,
        sigma: 0.036,
        beta: [0.5,1,0.666667],
        kn: 1,
        gn: 1,
        pattern: { w: 55, h: 51, data: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIFBwoKCgcFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAChkoMzo/PTUtIxkRBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFjNUcISOk4yCcF5MOigUAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIUlymb/Y5ejg0byjjHVbPx4HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI2CZxu3////////84saqjnBMJgoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFGO8///////////////52Lyed0wjBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFHB///////////////////gv5tyRBwCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFnT/////////////////////+C6kWAwDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///////////P/////8////////2Kp3RBwCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIz/////////7dPJ1uDi5e35//////nJkVYmBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHf/////////5beJcHqZssHR6Pz/////6KpoMAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAET8/////+W1pYxgMyM1W4Sjutby///////GfD0RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOg9P///9YrAAAAAAAAACFZgqPE6Pz/////4JNJFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFgt/L///84AAAAAAAAAAAAHFR/qtv8//////KjVBkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFF8te3///+OAAAAAAAAAAAAAAAZT4TJ+f/////5qlkcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKZ0/n//60AAAAAAAAAAAAAAAAAACZgtff/////96pZHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgvT//y0AAAAAAAAAAAAAAAAAAAAWVq3y/////+ibURkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIY78//8AAAAAAAAAAAAAAAAAAAAAK3LB9P/////RhEIRAAAAAAAAAAAAAAAAAAAAAAAAAAAAVLLv//9wAAAAAAAAAAAAAAAAAAAAAFSt6Pz/////tWswBwAAAAAAAAAAAAAAAAAAAAAAAAAAh+L////MbQoAAAAAAAAAAAAAAAAAAAB32///////8pNRHgAAAAAAAAAAAAAAAAAAAAAAAAAAAMT8//eTaFQtAAAAAAAAAAAAAAAAAAAAifL//////8xwNQ8AAAAAAAAAAAAAAAAAAAAAAAAAAGPT//+MHAwmOA8AAAAAAAAAAAAAAAAAAJP8//////+WSRwCAAAAAAAAAAAAAAAAAAAAAAAKjM7b9///fwAAAhYHAAAAAAAAAAAAAAAAAELG//////+oWSEHAAAAAAAAAAAAAAAAAAAAAAAAVP///////+0cAAAAAAAAAAAAAAAAAAAAOrry//////+eWR4AAAAAAAAAAAAAAAAAAAAAAAAAAIL/////////twAAAAAAAAAAAAAAAAAAAP////////+OPxYAAAAAAAAAAAAAAAAAAAAAAAAAHmD///+oFIz///8HAAAAAAAAAAAAAAAAAFn///////+qHgAAAAAAAAAAAAAAAAAAAAAAAACZ////////fAAA3f/gAAAAAAAAAAAAAAAAAAD///////+yEQAAAAAAAAAAAAAAAAAAAAAACjV6//////////8AAAprQgAAAAAAAAAAAB41VpP////89/x1AAAAAAAAAAAAAAAAAAAAAAAAAH//////9ABP////hwAAAAAAAAAAMzUAAABE////////3YQCAAAAAAAAAAAAAAAAAAAAAAAAANb//////wAAANP//4QAAAAAAAAAQtGWBQAAdf//////5YwAAAAAAAAAAAAAAAAAAAAAAAAAAGP8/////8YKAAAA7eoAAAAAAAAAAK///1sAAP//paj33YkAAAAAAAAAAAAAAAAAAAAAAACMv5a8//8AAL+1LQAAAAAAAAAAAABJAABy/////////3djtT8AAAAAAAAAAAAAAAAAAAAAAAAAr87M6v8hAAAh75MAAAAAAAAAAAD//1YACv////////89AAAAAAAAAAAAAAAAAAAAAAAAAAAAAKDY5fn/FgAABf+jAAAAAAAAAACW///WAAD///////+jAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACjpar//zUCAAoFAAAAAAAAAAAAr////0le//+ZoP/WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcLq62P/3OgwAAAAAAAAAAA8AAAD3////////VD2qAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHozl5f///20KAAAAAAAAAE+JAAAA4P///////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEm1/////8lHAAAAAAAAAABmxIkAAN3//////08AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKERot/z//9FrFgAAAAAAAAAAGYyTk8T8/////6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT3pydaDg/9OWRw8AAAAAAAAAAABRsvL/////spMeCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqJh3qRlqWgjFkhBwUWvP8WAAAAUdv/////kXBPKAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT3JPLUdjd4l/WTMoR7//awIAAJn/////gkkWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjTGaJtbylfFlEd5mZt/n/////pVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD1SHr+/8/9ZoKCb0/////////7ohAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABr2/n5/P/voFGe/////////6U6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARnvL///z5/P/////////5IwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB3Xi///307/O7//////8BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjkeDtzpNyeqPb9/z8awAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6cndjSTAzdUcHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUOD0mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABE4IwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
    },
];

export const patternCells = (preset) => decode(preset.pattern.data);
